### ISSUE TITLE
Nice to have features and todo list

### ISSUE THREAD

**Issue by bodleytunes** [bodleytunes/arista-dojo#4]
Todo List

- [ ]  Test bare bones / day zero spin-up using v2 image
- [ ] Ability to packet capture and TCPdump
- [x] Update docs and images to be stored in Git LFS
- [ ] IP each of the nodes to create barebones mesh
- [x] See if possible to force a static MAC address
